spring:
  application:
    name: todolist

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:4404/todolist
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  ssl:
    key-store: classpath:todolist.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: todolist
    key-password: password
  port: 8443
